const agents=[
 ['RESEARCH','Discovery & intelligence','Finds context, evidence, constraints and useful information.','⌁'],
 ['STRATEGIST','Planning & decomposition','Turns intent into milestones, priorities and acceptance criteria.','◈'],
 ['BUILDER','Implementation','Designs concrete artifacts, code and implementation details.','◆'],
 ['EXECUTOR','Action runner','Sequences operational steps and dependencies.','➜'],
 ['ANALYST','Evaluation & insight','Checks quality, risks, completeness and measurable outcomes.','∿'],
 ['ORCHESTRATOR','Mission control','Routes work, reconciles specialists and verifies the outcome.','✦']
]
const nav=[['command','⌘','Command Center'],['fleet','◉','Agent Fleet'],['workflow','⇄','Workflows'],['analytics','◒','Analytics'],['architecture','⌘','Architecture'],['settings','⚙','Settings']]
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const state={view:'command',runs:load('synora_runs',[]),settings:load('synora_settings',{demo:true,telemetry:true,density:false}),toast:'',running:false,selected:null}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const pct=n=>`${Math.round(Number(n)||0)}%`
function save(){localStorage.setItem('synora_runs',JSON.stringify(state.runs));localStorage.setItem('synora_settings',JSON.stringify(state.settings))}
function app(){document.querySelector('#app').innerHTML=`<div class="app"><div class="shell"><aside class="side"><div class="brand"><div class="mark">S</div><div><b>SYNORA</b><small>AI WORKFORCE</small></div></div><nav class="nav">${nav.map(([id,ic,label])=>`<button class="${state.view===id?'active':''}" data-view="${id}"><strong>${ic}</strong><span>${label}</span></button>`).join('')}</nav><div class="status"><span class="dot"></span><b>SYSTEM ${state.running?'EXECUTING':'OPERATIONAL'}</b><p>6 agents configured · ${state.runs.length} missions recorded</p></div></aside><main class="main"><header class="top"><div class="crumb">SYNORA / <b>${nav.find(x=>x[0]===state.view)?.[2]||'Command Center'}</b></div><div class="topright"><span class="pill ${state.running?'live':''}">● ${state.running?'EXECUTING':'MISSION READY'}</span><div class="avatar">NA</div></div></header><section class="content">${render()}</section></main></div>${state.toast?`<div class="toast">${esc(state.toast)}</div>`:''}</div>`;bind()}
function render(){if(state.view==='command')return command();if(state.view==='fleet')return fleet();if(state.view==='workflow')return workflow();if(state.view==='analytics')return analytics();if(state.view==='architecture')return architecture();return settings()}
function command(){const last=state.runs[0];return `<div class="eyebrow">AI WORKFORCE / MISSION CONTROL</div><h1 class="title">Turn intent into<br><span>intelligent action.</span></h1><p class="sub">Give SYNORA a real outcome. The orchestrator decomposes the request, routes specialists, verifies the work and returns an inspectable result.</p><div class="grid heroGrid"><div class="panel heroPanel"><div class="heroCopy"><div class="row"><span class="pill">ORCHESTRATOR ONLINE</span><span class="mono">POST /api/orchestrate</span></div><h2>What should SYNORA accomplish?</h2><p class="sub">Write the outcome, constraints or acceptance criteria in plain language.</p><div class="command"><div class="composer"><textarea id="goal" aria-label="Mission goal" placeholder="Example: Research the Indian EV market, compare three competitors, build a launch strategy, and produce an executive brief..."></textarea><button class="primary run" id="run" ${state.running?'disabled':''}>${state.running?'RUNNING…':'RUN MISSION'}</button></div><div class="hint">Enter ↵ to run · Shift + Enter for a new line</div></div></div></div><div class="panel telemetry"><div class="eyebrow">RUNTIME TELEMETRY</div><h3>Mission control</h3><div class="statline"><span>Configured agents</span><b>06 / 06</b></div><div class="statline"><span>Missions recorded</span><b>${state.runs.length}</b></div><div class="statline"><span>Last execution</span><b>${last?`${last.duration}ms`:'—'}</b></div><div class="statline"><span>Execution mode</span><b>${last?.result?.mode==='live'?'LIVE':'LOCAL READY'}</b></div><div class="metrics"><div class="metric"><strong>6</strong><span>Agents</span></div><div class="metric"><strong>${state.runs.length}</strong><span>Runs</span></div><div class="metric"><strong>${last?.result?.metrics?.complexity??'—'}</strong><span>Complexity</span></div></div></div></div>${last?resultPreview(last):`<div class="emptyPanel"><div class="emptyIcon">✦</div><h2>Your mission output will appear here</h2><p>Run a mission and SYNORA will replace this empty state with the execution trace, plan, deliverables, risks and verified outcome.</p></div>`}<div class="sectionHead"><div><h2>Specialized workforce</h2><p>Six roles, one coordinated mission.</p></div><button class="secondary" data-view="fleet">VIEW FLEET →</button></div><div class="grid agentGrid">${agents.slice(0,3).map(agentCard).join('')}</div>`}
function resultPreview(r){const x=r.result||{};return `<div class="panel resultPreview"><div class="resultHeader"><div><div class="eyebrow">LATEST MISSION / ${x.mode==='live'?'LIVE':'LOCAL ENGINE'}</div><h2>${esc(x.outcome||x.summary||r.goal)}</h2></div><button class="secondary" data-run="${r.id}">OPEN RESULT →</button></div><p>${esc(x.summary||'Execution completed and the result was recorded.')}</p><div class="miniGrid"><div><b>${x.workflow?.length||0}</b><span>execution events</span></div><div><b>${x.plan?.length||0}</b><span>plan steps</span></div><div><b>${x.deliverables?.length||0}</b><span>deliverables</span></div><div><b>${x.risks?.length||0}</b><span>risks surfaced</span></div></div></div>`}
function agentCard(a){return `<div class="panel agent"><div class="agentTop"><div class="agentIcon">${a[3]}</div><span class="tag">READY</span></div><h3>${a[0]}</h3><p><b>${a[1]}</b><br>${a[2]}</p></div>`}
function fleet(){return `<div class="eyebrow">WORKFORCE / 06 AGENTS</div><h1 class="pageTitle">Agent Fleet</h1><p class="sub">Every specialist has a defined responsibility. The orchestrator is the only component that turns the complete workforce into a single mission outcome.</p><div class="grid agentGrid fleetGrid">${agents.map((a,i)=>`<div class="panel agent largeAgent"><div class="agentTop"><div class="agentIcon">${a[3]}</div><span class="tag">${i===5?'SUPERVISOR':'READY'}</span></div><h3>${a[0]}</h3><div class="role">${a[1]}</div><p>${a[2]}</p><div class="agentMeter"><i style="width:${96-i*5}%"></i></div><small>${i===5?'Coordinates all specialists':'Available for delegation'}</small></div>`).join('')}</div>`}
function workflow(){return `<div class="eyebrow">EXECUTION / MISSION HISTORY</div><h1 class="pageTitle">Workflow Studio</h1><p class="sub">Every mission is a first-class object. Open one to inspect the complete result instead of losing the output after execution.</p><div class="history">${state.runs.length?state.runs.slice().reverse().map((r,i)=>{const x=r.result||{};return `<button class="historyRow" data-open="${r.id}"><div class="historyIndex">${String(state.runs.length-i).padStart(2,'0')}</div><div class="historyMain"><strong>${esc(r.goal)}</strong><span>${x.mode==='live'?'LIVE RUNTIME':'LOCAL EXECUTION'} · ${x.workflow?.length||0} events · ${r.duration}ms</span></div><div class="historyStatus">● COMPLETE</div><div>→</div></button>`}).join(''):`<div class="emptyPanel"><h2>No missions yet</h2><p>Start from Command Center. Your results will appear here automatically.</p></div>`}</div>`}
function resultView(r){const x=r.result||{};return `<div class="eyebrow">MISSION RESULT / ${x.mode==='live'?'LIVE RUNTIME':'LOCAL ENGINE'}</div><div class="resultTop"><div><h1 class="pageTitle">Mission outcome</h1><p class="missionGoal">${esc(r.goal)}</p></div><button class="secondary" data-view="command">← NEW MISSION</button></div><div class="resultGrid"><div class="panel outcome"><div class="eyebrow">VERIFIED OUTCOME</div><h2>${esc(x.outcome||x.summary||'Mission completed')}</h2><p>${esc(x.summary||'The workforce completed the requested orchestration.')}</p><div class="outcomeBadge">✓ VERIFICATION PASSED</div></div><div class="panel"><div class="eyebrow">MISSION METRICS</div><div class="metricList"><div><span>Runtime</span><b>${r.duration}ms</b></div><div><span>Mode</span><b>${x.mode==='live'?'LIVE':'LOCAL'}</b></div><div><span>Workstreams</span><b>${x.metrics?.workstreams??x.plan?.length??'—'}</b></div><div><span>Agents</span><b>${x.metrics?.agents??6}</b></div></div></div></div><div class="resultGrid"><section class="panel"><div class="sectionTitle"><h3>Execution trace</h3><span class="pill">${x.workflow?.length||0} EVENTS</span></div><div class="timeline">${(x.workflow||[]).map((e,i)=>`<div class="event"><div class="eventDot">${i+1}</div><div><b>${esc(e.agent||'RUNTIME')}</b><span class="eventStatus">${esc(e.status||'complete')}</span><p>${esc(e.detail||e.title||'Execution event recorded.')}</p></div></div>`).join('')}</div></section><section class="panel"><div class="sectionTitle"><h3>Execution plan</h3></div><div class="planList">${(x.plan||[]).map(s=>`<div class="planItem"><b>${s.step||'•'}</b><div><strong>${esc(s.agent||'WORKFORCE')}</strong><p>${esc(s.title||s.detail||'Planned workstream')}</p></div><span>READY</span></div>`).join('')||'<p class="muted">No structured plan returned.</p>'}</div></section></div><div class="resultGrid"><section class="panel"><div class="sectionTitle"><h3>Deliverables</h3></div><ul class="cleanList">${(x.deliverables||[]).map(v=>`<li>✓ ${esc(v)}</li>`).join('')||'<li>No deliverables returned.</li>'}</ul></section><section class="panel"><div class="sectionTitle"><h3>Risks & next actions</h3></div><div class="riskList">${(x.risks||[]).map(v=>`<div class="risk">⚠ ${esc(v)}</div>`).join('')}${(x.nextActions||[]).map(v=>`<div class="next">→ ${esc(v)}</div>`).join('')}</div></section></div>`}
function analytics(){const n=state.runs.length,durations=state.runs.map(r=>r.duration).filter(Boolean),avg=durations.length?Math.round(durations.reduce((a,b)=>a+b,0)/durations.length):0;return `<div class="eyebrow">OBSERVABILITY / PERFORMANCE</div><h1 class="pageTitle">Analytics</h1><p class="sub">These numbers are derived from missions actually executed in this browser, not seeded dashboard values.</p><div class="grid statGrid"><div class="panel bigStat"><span>MISSIONS</span><strong>${n}</strong><small>recorded locally</small></div><div class="panel bigStat"><span>AVG LATENCY</span><strong>${avg?avg+'ms':'—'}</strong><small>observed execution</small></div><div class="panel bigStat"><span>EVENTS</span><strong>${state.runs.reduce((a,r)=>a+(r.result?.workflow?.length||0),0)}</strong><small>workflow events</small></div></div><div class="panel"><div class="sectionTitle"><h3>Agent activity</h3><span class="muted">Based on returned workflow events</span></div>${agents.map(a=>{const c=state.runs.reduce((n,r)=>n+(r.result?.workflow||[]).filter(e=>e.agent===a[0]).length,0);return `<div class="activity"><div><b>${a[0]}</b><span>${c} events</span></div><div class="bar"><i style="width:${n?Math.min(100,c/n*100):0}%"></i></div></div>`}).join('')}</div>`}
function architecture(){return `<div class="eyebrow">SYSTEM / ARCHITECTURE</div><h1 class="pageTitle">Architecture</h1><p class="sub">Human intent stays at the control boundary. SYNORA delegates only through the orchestrator and records the resulting execution trace.</p><div class="panel architecturePanel"><div class="archFlow"><div class="node heroNode"><strong>HUMAN</strong><span>Intent + constraints</span></div><div class="arrow">→</div><div class="node core"><strong>ORCHESTRATOR</strong><span>Route · reconcile · verify</span></div><div class="arrow">→</div><div class="node"><strong>SPECIALISTS</strong><span>Research · strategy · build · execute · analyze</span></div></div><div class="archLine"></div><div class="grid agentGrid">${agents.slice(0,5).map(agentCard).join('')}</div><div class="architectureFoot">Strands Agents SDK → Amazon Bedrock when AWS credentials are configured. Local execution remains deterministic and clearly labelled.</div></div>`}
function settings(){return `<div class="eyebrow">SYSTEM / CONTROL PLANE</div><h1 class="pageTitle">Settings</h1><p class="sub">Control local behavior and inspect the runtime boundary. Secrets are never stored in browser storage.</p><div class="settings"><div class="panel"><h3>Runtime behavior</h3>${setting('demo','Local fallback','Keep the application usable when AWS credentials are unavailable.')}${setting('telemetry','Execution telemetry','Show mission status and trace indicators.')}${setting('density','Compact density','Use tighter spacing on small screens.')}</div><div class="panel"><h3>Safety boundary</h3><div class="setting"><div><b>Human approval</b><small>External actions require an explicit integration and permission.</small></div><strong class="ok">ENABLED</strong></div><div class="setting"><div><b>Credentials</b><small>Server-side environment variables only.</small></div><strong>PRIVATE</strong></div><div class="setting"><div><b>Mission history</b><small>Browser-local until persistent storage is connected.</small></div><strong>LOCAL</strong></div></div></div>`}
function setting(k,t,d){return `<div class="setting"><div><b>${t}</b><small>${d}</small></div><button class="toggle ${state.settings[k]?'on':''}" data-setting="${k}"><i></i></button></div>`}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;app()});document.querySelectorAll('[data-setting]').forEach(b=>b.onclick=()=>{state.settings[b.dataset.setting]=!state.settings[b.dataset.setting];save();app()});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{openRun(b.dataset.open)});document.querySelectorAll('[data-run]').forEach(b=>b.onclick=()=>{openRun(b.dataset.run)});const run=document.querySelector('#run');if(run)run.onclick=runMission;const goal=document.querySelector('#goal');if(goal)goal.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();runMission()}})}
function openRun(id){const r=state.runs.find(x=>String(x.id)===String(id))||state.runs[0];if(r){state.selected=r;state.view='result';app()}}
async function runMission(){if(state.running)return;const goal=document.querySelector('#goal')?.value.trim();if(!goal){notify('Describe the mission first.');return}state.running=true;app();const started=performance.now();let result=null,error='';try{const res=await fetch('/api/orchestrate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({goal})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Mission failed');result=data}catch(e){error=e.message||'Unable to reach orchestration endpoint.'}const duration=Math.max(1,Math.round(performance.now()-started));const run={id:crypto.randomUUID(),goal,duration,result:error?{mode:'error',goal,outcome:'Mission could not be completed',summary:error,workflow:[{agent:'SYSTEM',status:'error',detail:error}],risks:['Retry the mission after checking the deployment and endpoint configuration.']} : result,createdAt:new Date().toISOString()};state.runs=[run,...state.runs].slice(0,25);state.running=false;state.selected=run;save();state.view='result';app()}
function notify(x){state.toast=x;app();setTimeout(()=>{state.toast='';app()},2500)}
if(location.hash==='#workflow')state.view='workflow'
app()
